# Dockerfile
# Este arquivo é usado para construir uma imagem Docker baseada no NGINX e copiar um arquivo de configuração personalizado.

# Definir a imagem base como nginx
FROM nginx:latest

# Copiar o arquivo de configuração personalizado para o diretório de configuração do NGINX
COPY default.conf /etc/nginx/conf.d/default.conf